# Generated by Django 3.0.7 on 2020-06-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_image_upl', '0002_img_url_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='image',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='img',
            old_name='url_img',
            new_name='url',
        ),
    ]
