# Generated by Django 3.0.7 on 2020-06-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_image_upl', '0003_auto_20200620_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
