# Generated by Django 3.0.7 on 2020-06-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_image_upl', '0004_img_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='file',
            field=models.ImageField(blank=True, upload_to='static/test_image_upl/images'),
        ),
    ]
